#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║              WEEK 1 MVP - 30 MINUTE STREAMING TEST             ║"
echo "║              Complete Terminal Command Guide                   ║"
echo "║                                                                ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 GOAL: Prove 30+ minute continuous streaming with screen sleep survival"
echo ""

echo "══════════════════════════════════════════════════════════════════"
echo "STEP 1: BUILD & INSTALL ANDROID APP"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo "📱 Run these commands in Terminal 1:"
echo ""
echo "cd /Users/atorrella/Desktop/Miktos/Mobile/Android"
echo "./gradlew clean"
echo "./gradlew assembleDebug" 
echo "./gradlew installDebug"
echo ""
echo "⚠️  Make sure Samsung S23 FE is connected via USB with Developer Mode enabled"
echo ""

echo "══════════════════════════════════════════════════════════════════"
echo "STEP 2: START DESKTOP RECEIVER" 
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo "🖥️  Run this command in Terminal 2 (keep this window visible for monitoring):"
echo ""
echo "cd /Users/atorrella/Desktop/Miktos/Mobile/Receivers"
echo "python3 android_receiver.py"
echo ""
echo "✅ You should see: 'Server listening on 0.0.0.0:8554'"
echo ""

echo "══════════════════════════════════════════════════════════════════"
echo "STEP 3: CONFIGURE SAMSUNG S23 FE STREAMING"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo "📱 On your Samsung S23 FE:"
echo "   1. Open 'StreamLabCamera' app"
echo "   2. Enter connection settings:"
echo "      • Server IP: 192.168.2.36"
echo "      • Port: 8554" 
echo "   3. Tap 'START STREAMING'"
echo "   4. Verify green 'STREAMING' indicator appears"
echo ""

echo "══════════════════════════════════════════════════════════════════"
echo "STEP 4: START 30-MINUTE TEST + SCREEN RECORDING"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo "🎬 Run this command in Terminal 3 to start screen recording:"
echo ""
echo "# Record Mac screen showing live streaming (saves to Desktop)"
echo "ffmpeg -f avfoundation -i \"1:0\" -r 30 -vf \"scale=1920:1080\" \\"
echo "       -c:v libx264 -preset fast -crf 23 \\"
echo "       ~/Desktop/Miktos_30min_Streaming_Test_\$(date +%Y%m%d_%H%M%S).mp4"
echo ""
echo "🔴 This will record your entire screen - position FFplay window prominently"
echo ""

echo "══════════════════════════════════════════════════════════════════"
echo "STEP 5: MONITOR & VERIFY (During 30+ Minutes)"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo "✅ CHECKLIST TO VERIFY:"
echo ""
echo "   □ FFplay window shows live video from phone camera"
echo "   □ Terminal 2 shows 'Connected client from: ...' message"
echo "   □ Phone shows persistent notification 'StreamLabCamera is running'"
echo "   □ Let phone screen go to sleep naturally (after ~30 seconds)"
echo "   □ Verify streaming continues with dark/sleeping phone screen"
echo "   □ At 15 minutes: Unlock phone once, verify stream doesn't disconnect"
echo "   □ Let phone sleep again, continue to 30+ minutes"
echo "   □ Record bitrate/quality stats from Terminal 2 output"
echo ""

echo "══════════════════════════════════════════════════════════════════"
echo "STEP 6: STOP RECORDING & COLLECT RESULTS"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo "⏹️  After 30+ minutes, stop everything:"
echo ""
echo "   1. Press Ctrl+C in Terminal 3 (stop screen recording)"
echo "   2. Stop streaming on Samsung S23 FE"  
echo "   3. Press Ctrl+C in Terminal 2 (stop receiver)"
echo ""
echo "📁 Your proof video will be saved to:"
echo "   ~/Desktop/Miktos_30min_Streaming_Test_[timestamp].mp4"
echo ""

echo "══════════════════════════════════════════════════════════════════"
echo "🚀 READY TO START? COPY THESE EXACT COMMANDS:"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo "# Terminal 1 - Build Android App:"
echo "cd /Users/atorrella/Desktop/Miktos/Mobile/Android && ./gradlew clean assembleDebug installDebug"
echo ""
echo "# Terminal 2 - Start Receiver:"  
echo "cd /Users/atorrella/Desktop/Miktos/Mobile/Receivers && python3 android_receiver.py"
echo ""
echo "# Terminal 3 - Start Recording:"
echo "ffmpeg -f avfoundation -i \"1:0\" -r 30 -vf \"scale=1920:1080\" -c:v libx264 -preset fast -crf 23 ~/Desktop/Miktos_30min_Test_\$(date +%Y%m%d_%H%M%S).mp4"
echo ""
echo "🎯 SUCCESS CRITERIA:"
echo "   ✅ 30+ minutes continuous streaming"
echo "   ✅ Survives screen sleep"  
echo "   ✅ Notification stays visible"
echo "   ✅ Can unlock phone without disconnect"
echo "   ✅ Stable video quality in FFplay"
echo ""
echo "🎉 YOU'VE GOT THIS! Your app already streamed 9:49 successfully!"
echo "   The FLAG_KEEP_SCREEN_ON protection should solve any remaining issues."
echo ""